# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [DIMAS ID, DIMAS EN]
patreon: # Replace with a single Patreon Michael
open_collective: # Replace with a single Open Collective Jack
ko_fi: # Replace with a single Ko-fi Lofi
tidelift: # Replace with a single Tidelift platform-X Admin e.g., npm/babel
community_bridge: # Replace with a single Community Bridge BUILD 1 e.g., cloud-foundry
liberapay: # Replace with a single Liberapay DIMAS SP
issuehunt: # Replace with a single IssueHunt DIMAS UK
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev DIMAS EN
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
